language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-5
      env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      before_script:
        - python scripts/lint.py

    - os: linux
      dist: xenial
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-7
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          packages: clang-5.0
      env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    - os: linux
      dist: xenial
      compiler: clang

    - os: osx
      osx_image: xcode10.1

    - os: osx
      osx_image: xcode9.4

before_install:
- eval "${MATRIX_EVAL}"

install:
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install open-mpi libomp tbb; fi
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install lam-runtime; fi
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install mpich openmpi-bin libopenmpi-dev; fi
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install libomp-dev libtbb-dev; fi

script:
- python scripts/lint.py
- mkdir build
- cd build
- cmake -D USE_MPI=ON -D USE_OMP=ON -D USE_TBB=ON -D CMAKE_BUILD_TYPE=RELEASE ..
- cmake --build .
- cd ..
- export OMP_NUM_THREADS=4
- source scripts/run.sh

notifications:
  email: false
